#!/usr/bin/env python

import sys
import os


def application(environ, start_response):
    ctype = 'text/plain'
    if environ['PATH_INFO'] == '/env':
        response_body = '\n'.join(['%s => %s' % (key, value) for key, value in sorted(environ.items())])
    elif environ['PATH_INFO'] == '/os':
        response_body = '\n'.join(['%s => %s' % (key, value) for key, value in sorted(os.environ.items())])
    elif environ['PATH_INFO'] == '/send':
        import send
        ctype, response_body = send.Send(environ)
    else:
        response_body = 'Gtalk!'

    response_headers = [('Content-Type', ctype), ('Content-Length', str(len(response_body)))]
    status = '200 OK'
    start_response(status, response_headers)
    return [response_body]


if __name__ == "__main__":
    from wsgiref.simple_server import make_server
    httpd = make_server('0.0.0.0', 8080, application)
    httpd.handle_request()
